function graficFTJ 
 
figure('Name','Proiect Filtru RC Trece Jos ',...  
 'Units','normalized',... 
 'Position',[0.1 0.09 0.8 0.83],...
 'NumberTitle','off');
set(gcf, 'Color',[0.75 0.75 0.75]);

%Titlu
   uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.25 0.92 0.5 0.08],...
        'backgroundcolor',[0.52 0.18 0.23],...',...
        'foregroundcolor',[0.8500 0.3250 0.0980],...
        'Fontname','Times New Roman',...
        'FontWeight','Bold',...
        'FontSize',35,...
        'String','Filtru RC Trece Jos');
  
 %Citire imagine Filtru RL Trece jos
 uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.33 0.82 0.3 0.1],...
        'backgroundcolor',[0.52 0.18 0.23],...
        'foregroundcolor',[0.8500 0.3250 0.0980],...
        'FontWeight','Bold',...
        'Fontname','Comic Sans MS',...
        'FontSize',25,...
        'String','~Schema circuitului~'); 
 subplot('position',[0.13 0.23 0.72 0.58]);
 z = imread('RC.jpg');
 image(z); 
 axis off;
 
 
uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.16 0.08 0.205 0.1],...
          'string','Diagrame FTJ',...
          'FontName','Comic Sans MS',...
          'FontSize',19,... 
          'FontWeight','Bold',...
          'backgroundcolor',[0.52 0.18 0.23],...
          'foregroundcolor',[0.8500 0.3250 0.0980],...
          'Callback','start');

uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.6 0.08 0.205 0.1],...
          'string','Inapoi',...
          'FontName','Comic Sans MS',...
          'backgroundcolor',[0.52 0.18 0.23],...
          'foregroundcolor',[0.8500 0.3250 0.0980],...
          'FontSize',19,... 
          'FontWeight','Bold',...
          'Callback','pagina_principala');