function reprezentare_FTJ(R,C,P,sel)

%Crearea ferestrei de lucru
figure('Name','Caracteristicile de frecventa unui FTJ',...
           'Units','normalized',...
           'Position',[0.2 0.2 0.6 0.4],...
           'color',[0.93 0.91 0.8],...
           'NumberTitle','off');


 %Titlu
   uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.01 0.920 0.36 0.08],...
        'backgroundcolor',[0.93 0.91 0.8],...',...
        'foregroundcolor',[0 0 0],...
        'Fontname','Times New Roman',...
        'FontWeight','Bold',...
        'FontSize',20,...
        'String','Caracteristicile de frecventa ale FTJ');
    
   

%Initializare marimi specifice filtrului
 f0=1./(2.*pi.*R.*C);
 w0=2.*pi.*f0;
 w=logspace(-1,10,P);
 f=w/(2*pi);
 numarator=1;
 numitor=1 + 1i*w*R*C;
 H=abs(numarator./numitor);
 Castig=20*log10(H);
 faza=angle(numarator./numitor)*180./pi;
 
%Grup afisare Semnal
GroupAfis=uibuttongroup('Visible','on',...
    'FontWeight', 'bold',...
    'BackgroundColor',[0.93 0.91 0.8],...
    'ForegroundColor','black',...
    'Fontname','Comic Sans MS',...
    'Title','Semnal:',...
    'FontSize',17,...
    'TitlePosition','centertop',...
    'Position',[0.027 0.082 0.3 0.13]);
 
% GRID
uicontrol('style','text',...
          'Units','normalized',...
          'String','Grid:',...
           'BackgroundColor',[0.93 0.91 0.8],...
           'ForegroundColor','black',...
          'FontWeight', 'bold',...
          'FontSize',12,...
          'Position',[0.05 0.3 0.5 0.4],...
          'Parent',GroupAfis);
 
    RadioB1=uicontrol('style','radiobutton',...
          'Units','normalized',...
           'BackgroundColor',[0.93 0.91 0.8],...
           'ForegroundColor','black',...
          'String','ON',...
          'FontWeight', 'bold',...
          'FontSize',12,...
          'Position',[0.5 0.3 0.5 0.4],...
          'Parent',GroupAfis,...
          'Callback','sel=1,close;reprezentare_FTJ(R,C,P,sel);');
      
      RadioB2=uicontrol('style','radiobutton',...
          'Units','normalized',...
           'BackgroundColor',[0.93 0.91 0.8],...
           'ForegroundColor','black',...
          'String','OFF',...
          'FontWeight', 'bold',...
          'FontSize',12,...
          'Position',[0.7 0.3 0.5 0.4],...
          'Parent',GroupAfis,...
          'Callback','sel=2,close;reprezentare_FTJ(R,C,P,sel);');

   

%Reprezentare Uin/Uout

 subplot('Position', [0.4 0.73 0.5 0.22]);
 semilogx(f,H,'b',f0,1./sqrt(2),'d','LineWidth',2);
 xlabel('Frecventa [ Hz ]');
 ylabel('| U2 / U1 | ');
 title('Caracteristica  |U2 / U1 |', ...
       'Fontweight','b','Color','black');
 legend(' |U2 / U1 |');
 
 if sel == 1
set(RadioB1,'value',1)
set(RadioB2,'value',0)
grid on;
else
set(RadioB1,'value',0)
set(RadioB2,'value',1)
grid off;
 end

%Reprezentare faza
 subplot('Position', [0.4 0.08 0.5 0.22]);
 semilogx(f,faza,'r',f0,-45,'d','LineWidth',2);
 xlabel('Frecventa [ Hz ]');
 ylabel('Faza [ grade ]');
 title('Faza semnalului',...
       'Fontweight','b','Color','black');
 legend('Faza');
 
 if sel == 1
set(RadioB1,'value',1)
set(RadioB2,'value',0)
grid on;
else
set(RadioB1,'value',0)
set(RadioB2,'value',1)
grid off;
 end

%Reprezentare Castig
 
 subplot('Position', [0.4 0.41 0.5 0.22]);
 semilogx(f,Castig,'c',f0,-3,'d','LineWidth',2);
 xlabel('Frecventa [ Hz ]');
 ylabel('Castigul [ dB ]');
 title('Castigul','fontweight','b','Color','black');
 legend('Castigul');
 
if sel == 1
set(RadioB1,'value',1)
set(RadioB2,'value',0)
grid on;
else
set(RadioB1,'value',0)
set(RadioB2,'value',1)
grid off;
end

%Buton Inapoi
 uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.13 0.012 0.1 0.05],...
          'string','Inapoi',...
          'FontName','Comic Sans MS',...
          'FontWeight','Bold',...
          'backgroundcolor',[0.8500 0.3250 0.0980],...
          'foregroundcolor',[0 0 0],...
          'FontSize',19,...          
          'Callback','pagina_principala;');

%Uibuttongroup Date si calcule
RadioGroup0=uibuttongroup('Visible','on',...
        'BackgroundColor',[0.93 0.91 0.8],...
        'ForegroundColor','black',...
        'Title','Date si calcule',...
        'FontSize',21,...
        'Position',[0.025 0.21 0.3 0.72],...
        'FontWeight','Bold',...
        'TitlePosition','centertop',...
        'Fontname','Comic Sans MS',...
        'Tag','radiobutton');

%Grup de butoane parametrii circuitului
%Grup Valori numerice
RadioGroup1=uibuttongroup('Visible','on',...
        'BackgroundColor',[0.93 0.91 0.8],...
        'ForegroundColor','black',...
        'Title','Valori numerice',...
        'FontSize',19,...
        'Position',[0.11 0.42 0.78 0.55],...
        'FontWeight','Bold',...
        'Fontname','Comic Sans MS',...
        'TitlePosition','centertop',...
        'Parent',RadioGroup0,...
        'Tag','radiobutton');

    %Valoare rezistenta
uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.19 0.750 0.4 0.23],...
        'backgroundcolor',[0.8500 0.3250 0.0980],...
        'foregroundcolor','black',...
        'FontSize',15,...
        'String','R[Ohm]',...
        'FontWeight','Bold',...
        'Parent',RadioGroup1);
uicontrol('Style','edit',...
        'Units','normalized',...
        'Position',[0.65 0.75 0.3 0.23],...
        'FontSize',15,...
        'String', R,...
        'FontWeight','Bold',...
        'Parent',RadioGroup1,...
        'Callback','R=str2num(get(gco,''String'')),close,reprezentare_FTJ(R,C,P,sel)');
    
     %Valoare capacitate
uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.19 0.45 0.4 0.23],...
        'backgroundcolor',[0.8500 0.3250 0.0980],...
        'foregroundcolor','black',...
        'FontSize',15,...
        'FontWeight','Bold',...
        'String','C[Farad]',...
        'Parent',RadioGroup1);
uicontrol('Style','edit',...
        'Units','normalized',...
        'Position',[0.65 0.45 0.3 0.23],...
        'FontSize',15,...
        'String', C,...
        'FontWeight','Bold',...
        'Parent',RadioGroup1,...
        'Callback','C=str2num(get(gco,''String'')),close,reprezentare_FTJ(R,C,P,sel)');

    %Valoare precizie
 uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.19 0.15 0.4 0.23],...
        'backgroundcolor',[0.8500 0.3250 0.0980],...
        'foregroundcolor','black',...
        'FontSize',15,...
        'FontWeight','Bold',...
        'String','Precizie',...
        'Parent',RadioGroup1);
uicontrol('Style','edit',...
        'Units','normalized',...
        'Position',[0.65 0.15 0.3 0.23],...
        'FontSize',15,...
        'String', P,...
        'FontWeight','Bold',...
        'Parent',RadioGroup1,...
        'Callback','P=str2num(get(gco,''String'')),close,reprezentare_FTJ(R,C,P,sel)');
    
  %Grup pentru calculul frecventei de taiere      
RadioGroup2=uibuttongroup('Visible','on',...
        'BackgroundColor',[0.93 0.91 0.8],...
        'ForegroundColor','black',...
        'Title','Frecventa de taiere',...
        'FontSize',15,...
        'Position',[0.1 0.1 0.8 0.30],...
        'FontWeight','Bold',...
        'Fontname','Comic Sans MS',...
        'TitlePosition','centertop',...
        'Parent',RadioGroup0,...
        'Tag','radiobutton');
uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.1 0.025 0.86 0.7],...
        'backgroundcolor',[0.8500 0.3250 0.0980],...
        'foregroundcolor','black',...
        'FontWeight','Bold',...
        'FontSize',15,...
        'String',['Fo[Hz] = ',num2str(f0)],...
        'Parent',RadioGroup2);

    %Calcul pulsatie      
RadioGroup3=uibuttongroup('Visible','on',...
        'BackgroundColor',[0.93 0.91 0.8],...
        'ForegroundColor','black',...
        'Title','Pulsatia',...
        'FontSize',15,...
        'Position',[0.1 0.010 0.8 0.18],...
        'FontWeight','Bold',...
        'Fontname','Comic Sans MS',...
        'TitlePosition','centertop',...
        'Parent',RadioGroup0,...
        'Tag','radiobutton');
uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.1 0.025 0.86 0.7],...
        'backgroundcolor',[0.8500 0.3250 0.0980],...
        'foregroundcolor','black',...
        'FontWeight','Bold',...
        'FontSize',15,...
        'String',['wo[rad/s]= ',num2str(w0)],...
        'Parent',RadioGroup3);